version: '3.8'

services:
  web:
    image: php:8.3-apache
    container_name: php_apache_server
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    restart: always

  # MySQLサービスの追加が必要な場合はコメントを解除してください
  # db:
  #   image: mysql:5.7
  #   container_name: mysql_server
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always

# データベース用のボリューム設定
#volumes:
#  db_data:

